/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gema.java;
import java.io.*;
import java.net.*;
import javax.swing.JOptionPane; // Para mostrar ventanas emergentes con mensajes
/**
 *
 * @author gbara
 */
public class Eliminar extends javax.swing.JFrame {

    /**
     * Creates new form Eliminar
     */
    public Eliminar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCedula1 = new javax.swing.JLabel();
        txtCedula1 = new javax.swing.JTextField();
        lblCedula = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        btnEliminarClientes = new javax.swing.JButton();
        btnEliminacion = new javax.swing.JButton();
        lblRegresar = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCedula1.setFont(new java.awt.Font("Century Gothic", 2, 18)); // NOI18N
        lblCedula1.setForeground(new java.awt.Color(255, 255, 255));
        lblCedula1.setText("Cedula Cliente:");
        getContentPane().add(lblCedula1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 220, 30));

        txtCedula1.setFont(new java.awt.Font("Century Gothic", 2, 12)); // NOI18N
        txtCedula1.setToolTipText("Ingrese Cedula");
        getContentPane().add(txtCedula1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 250, -1));

        lblCedula.setFont(new java.awt.Font("Century Gothic", 2, 18)); // NOI18N
        lblCedula.setForeground(new java.awt.Color(255, 255, 255));
        lblCedula.setText("Cedula Administrador:");
        getContentPane().add(lblCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 220, 30));

        txtCedula.setFont(new java.awt.Font("Century Gothic", 2, 12)); // NOI18N
        txtCedula.setToolTipText("Ingrese Cedula");
        getContentPane().add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 250, -1));

        btnEliminarClientes.setBackground(new java.awt.Color(204, 204, 204));
        btnEliminarClientes.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        btnEliminarClientes.setForeground(new java.awt.Color(153, 0, 153));
        btnEliminarClientes.setText("Eliminacion Cliente");
        btnEliminarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarClientesActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminarClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, -1, -1));

        btnEliminacion.setBackground(new java.awt.Color(204, 204, 204));
        btnEliminacion.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        btnEliminacion.setForeground(new java.awt.Color(153, 0, 153));
        btnEliminacion.setText("Eliminacion Administrador");
        btnEliminacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminacionActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, -1, -1));

        lblRegresar.setFont(new java.awt.Font("Century Gothic", 2, 12)); // NOI18N
        lblRegresar.setForeground(new java.awt.Color(255, 255, 255));
        lblRegresar.setText("Regresar");
        lblRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegresarMouseClicked(evt);
            }
        });
        getContentPane().add(lblRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, -1, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inicioo.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-300, 0, 1110, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminacionActionPerformed
       try {
            String cedulaABorrar = txtCedula.getText(); // Obtener la cédula del usuario actual
            cedulaABorrar = cedulaABorrar.trim();
            // Establecer una conexión con el servidor
            Socket socket = new Socket("localhost", 8888); // Cambia "localhost" y el puerto según corresponda

            // Enviar solicitud de borrado al servidor
            String solicitudBorrado = "BORRADOADMIN " + cedulaABorrar;
            OutputStream outputStream = socket.getOutputStream();
            PrintWriter writer = new PrintWriter(outputStream, true);
            writer.println(solicitudBorrado);

            // Esperar la respuesta del servidor
            InputStream inputStream = socket.getInputStream();
            BufferedReader reader = new BufferedReader(new InputStreamReader(inputStream));

            // Leer la respuesta del servidor
            String respuesta = reader.readLine();

            // Cerrar la conexión con el servidor
            socket.close();

            // Mostrar un mensaje de confirmación al usuario
            JOptionPane.showMessageDialog(null, respuesta, "Borrado de registro", JOptionPane.INFORMATION_MESSAGE);

            // Cerrar la aplicación
            System.exit(0);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error al borrar el registro: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminacionActionPerformed

    private void lblRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegresarMouseClicked
        // Regresar al login
        // Ir a la ventana registro
        dispose();
        new Inicio().setVisible(true);
    }//GEN-LAST:event_lblRegresarMouseClicked

    private void btnEliminarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarClientesActionPerformed
        try {
            String cedulaABorrar = txtCedula1.getText(); // Obtener la cédula del usuario actual
            cedulaABorrar = cedulaABorrar.trim();
            // Establecer una conexión con el servidor
            Socket socket = new Socket("localhost", 8888); // Cambia "localhost" y el puerto según corresponda

            // Enviar solicitud de borrado al servidor
            String solicitudBorrado = "BORRADO " + cedulaABorrar;
            OutputStream outputStream = socket.getOutputStream();
            PrintWriter writer = new PrintWriter(outputStream, true);
            writer.println(solicitudBorrado);

            // Esperar la respuesta del servidor
            InputStream inputStream = socket.getInputStream();
            BufferedReader reader = new BufferedReader(new InputStreamReader(inputStream));

            // Leer la respuesta del servidor
            String respuesta = reader.readLine();

            // Cerrar la conexión con el servidor
            socket.close();

            // Mostrar un mensaje de confirmación al usuario
            JOptionPane.showMessageDialog(null, respuesta, "Borrado de registro", JOptionPane.INFORMATION_MESSAGE);

            // Cerrar la aplicación
            System.exit(0);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error al borrar el registro: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarClientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Eliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Eliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Eliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Eliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Eliminar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton btnEliminacion;
    private javax.swing.JButton btnEliminarClientes;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblCedula1;
    private javax.swing.JLabel lblRegresar;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCedula1;
    // End of variables declaration//GEN-END:variables
}
