/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gema.java;
import java.io.*;
import java.net.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author gbara
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBorrado = new javax.swing.JButton();
        btnIncluye = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        listAdmi = new javax.swing.JScrollPane();
        jLista = new javax.swing.JList<>();
        gdTabla = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBorrado.setBackground(new java.awt.Color(204, 153, 255));
        btnBorrado.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        btnBorrado.setText("Borrado");
        btnBorrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorradoActionPerformed(evt);
            }
        });
        getContentPane().add(btnBorrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 420, -1, -1));

        btnIncluye.setBackground(new java.awt.Color(204, 153, 255));
        btnIncluye.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        btnIncluye.setText("Incluye");
        btnIncluye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluyeActionPerformed(evt);
            }
        });
        getContentPane().add(btnIncluye, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 420, -1, -1));

        btnModificar.setBackground(new java.awt.Color(204, 153, 255));
        btnModificar.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(51, 51, 51));
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, -1, -1));

        btnConsultar.setBackground(new java.awt.Color(204, 153, 255));
        btnConsultar.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, -1, -1));

        jLista.setBackground(new java.awt.Color(204, 102, 255));
        jLista.setForeground(new java.awt.Color(255, 255, 255));
        jLista.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Cedula:", "Nombre:", "Apellido:", "Segundo Apeliido:", "Telefono:", "Correo:", "Puesto:", "Contraseña:" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listAdmi.setViewportView(jLista);

        getContentPane().add(listAdmi, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 140, 390));

        Tabla.setAutoCreateRowSorter(true);
        Tabla.setBackground(new java.awt.Color(102, 102, 255));
        Tabla.setFont(new java.awt.Font("Segoe UI", 3, 11)); // NOI18N
        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cedula", "Nombre", "Apellido", "SegundoAepllido", "Telefono", "Correo", "Direccion", "Contraseña"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        gdTabla.setViewportView(Tabla);

        getContentPane().add(gdTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 610, 360));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inicioo.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-470, 0, 1300, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
         // Establecer una conexión con el servidor
    
        String serverAddress = "127.0.0.1";
        int serverPort = 8888;

        try {
            Socket socket = new Socket(serverAddress, serverPort);

            OutputStream outputStream = socket.getOutputStream();
            PrintWriter writer = new PrintWriter(outputStream, true);

            String solicitud = "TODO ";
            writer.println(solicitud);

            InputStream inputStream = socket.getInputStream();
            BufferedReader reader = new BufferedReader(new InputStreamReader(inputStream));

            StringBuilder respuesta = new StringBuilder();
            String linea;
            while ((linea = reader.readLine()) != null) {
                respuesta.append(linea).append("\n");
            }

            if (respuesta != null) {
                if (!respuesta.toString().trim().equals("ERROR")) {
                    String[] registros = respuesta.toString().split("\n");

                    DefaultTableModel model = (DefaultTableModel) Tabla.getModel();
                    model.setRowCount(0);

                    for (String registro : registros) {
                        String[] columns = registro.split(",");
                        if (columns.length >= 8) {
                            model.addRow(new Object[]{columns[0], columns[1], columns[2], columns[3], columns[4], columns[5], columns[6], columns[7]});
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Error al consultar los registros.");
                }
            }

            socket.close();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error de conexión: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnIncluyeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluyeActionPerformed
        // TODO add your handling code here:
        dispose();
        new Incluye().setVisible(true);
    }//GEN-LAST:event_btnIncluyeActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        dispose();
        new ModificarAdmi().setVisible(true);
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnBorradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorradoActionPerformed
        // TODO add your handling code here:
        dispose();
        new Eliminar().setVisible(true);
    }//GEN-LAST:event_btnBorradoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JTable Tabla;
    private javax.swing.JButton btnBorrado;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnIncluye;
    private javax.swing.JButton btnModificar;
    private javax.swing.JScrollPane gdTabla;
    private javax.swing.JList<String> jLista;
    private javax.swing.JScrollPane listAdmi;
    // End of variables declaration//GEN-END:variables
}
