/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gema.java;
import java.io.*;
import java.net.*;
import javax.swing.*;

/**
 *
 * @author gbara
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCuenta = new javax.swing.JLabel();
        btnSesion = new javax.swing.JButton();
        txtContraseña = new javax.swing.JPasswordField();
        txtCedula = new javax.swing.JTextField();
        Contraseña = new javax.swing.JLabel();
        Cedula = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Login"); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCuenta.setFont(new java.awt.Font("Century Gothic", 2, 12)); // NOI18N
        lblCuenta.setForeground(new java.awt.Color(255, 255, 255));
        lblCuenta.setText("Registrar Administrador");
        lblCuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCuentaMouseClicked(evt);
            }
        });
        getContentPane().add(lblCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, -1, -1));

        btnSesion.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        btnSesion.setForeground(new java.awt.Color(204, 51, 255));
        btnSesion.setText("Iniciar Sesion");
        btnSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSesionActionPerformed(evt);
            }
        });
        getContentPane().add(btnSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, -1, -1));

        txtContraseña.setFont(new java.awt.Font("Century Gothic", 2, 12)); // NOI18N
        getContentPane().add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 240, -1));

        txtCedula.setFont(new java.awt.Font("Segoe UI", 3, 11)); // NOI18N
        txtCedula.setToolTipText("Ingrese Usuario");
        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });
        getContentPane().add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 250, 30));

        Contraseña.setFont(new java.awt.Font("Century Gothic", 2, 24)); // NOI18N
        Contraseña.setForeground(new java.awt.Color(255, 255, 255));
        Contraseña.setText("Contraseña:");
        getContentPane().add(Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, -1, -1));

        Cedula.setFont(new java.awt.Font("Century Gothic", 2, 24)); // NOI18N
        Cedula.setForeground(new java.awt.Color(255, 255, 255));
        Cedula.setText("Usuario:");
        getContentPane().add(Cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/login.jpg"))); // NOI18N
        jLabel1.setName("jblFondo"); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 410));
        jLabel1.getAccessibleContext().setAccessibleName("jblFondo");
        jLabel1.getAccessibleContext().setAccessibleParent(jLabel1);

        getAccessibleContext().setAccessibleName("Login");
        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActionPerformed

    private void lblCuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCuentaMouseClicked
        // Ir a la ventana registro
        dispose();
        new Registro().setVisible(true);
    }//GEN-LAST:event_lblCuentaMouseClicked

    private void btnSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSesionActionPerformed
        // Ir a la ventana principal
        String cedula = txtCedula.getText();
        char[] contrasenaChars = txtContraseña.getPassword();
        String contrasena = new String(contrasenaChars);
        try {
            // Establecer una conexión con el servidor
            Socket socket = new Socket("localhost", 8888);

            // Crear un stream de escritura para enviar la solicitud al servidor
            OutputStream outputStream = socket.getOutputStream();
            PrintWriter writer = new PrintWriter(outputStream, true);

            // Construir la solicitud en el formato adecuado
            String solicitud = "LODIN " + cedula + " & " + contrasena;
            writer.println(solicitud);

            // Crear un lector de entrada para recibir la respuesta del servidor
            InputStream inputStream = socket.getInputStream();
            BufferedReader reader = new BufferedReader(new InputStreamReader(inputStream));

            // Leer la respuesta del servidor
            String respuesta = reader.readLine();

            // Verificar la respuesta del servidor
            if (respuesta != null) {
                if (respuesta.trim().equals("Inicio de sesion exitoso")) {
                    JOptionPane.showMessageDialog(this, "Inicio de sesión exitoso.");
                    dispose();
                    new Inicio().setVisible(true);
                } else if (respuesta.trim().equals("Cedula o contrasena incorrecta")) {
                    JOptionPane.showMessageDialog(this, "Error: Cédula o contraseña incorrecta.");
                } else {
                    JOptionPane.showMessageDialog(this, "Error desconocido.");
                }
            }

            // Cerrar la conexión con el servidor
            socket.close();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error de conexión: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cedula;
    private javax.swing.JLabel Contraseña;
    private javax.swing.JButton btnSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCuenta;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JPasswordField txtContraseña;
    // End of variables declaration//GEN-END:variables
}
