/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gema.java;
import java.io.*;
import java.net.*;
import javax.swing.JOptionPane; // Para mostrar ventanas emergentes con mensajes
/**
 *
 * @author gbara
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSolicitud = new javax.swing.JButton();
        txtContraseña = new javax.swing.JPasswordField();
        txtDireccion = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txttelefono = new javax.swing.JTextField();
        txtSApellido = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        lblRegresar = new javax.swing.JLabel();
        lblContraseña = new javax.swing.JLabel();
        lblPuesto = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblSApellido = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblCedula = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSolicitud.setBackground(new java.awt.Color(204, 204, 204));
        btnSolicitud.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        btnSolicitud.setForeground(new java.awt.Color(153, 0, 153));
        btnSolicitud.setText("Enviar Solicitud");
        btnSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolicitudActionPerformed(evt);
            }
        });
        getContentPane().add(btnSolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, -1, -1));
        getContentPane().add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, 240, -1));

        txtDireccion.setFont(new java.awt.Font("Century Gothic", 2, 12)); // NOI18N
        txtDireccion.setToolTipText("Ingrese Direccion");
        getContentPane().add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 250, -1));

        txtCorreo.setFont(new java.awt.Font("Century Gothic", 2, 12)); // NOI18N
        txtCorreo.setToolTipText("Ingrese Correo");
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        getContentPane().add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 250, -1));

        txttelefono.setFont(new java.awt.Font("Century Gothic", 2, 12)); // NOI18N
        txttelefono.setToolTipText("Ingrese Telefono");
        getContentPane().add(txttelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 250, -1));

        txtSApellido.setFont(new java.awt.Font("Century Gothic", 2, 12)); // NOI18N
        txtSApellido.setToolTipText("Ingrese Segundo Apellido");
        getContentPane().add(txtSApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, 250, -1));

        txtApellido.setFont(new java.awt.Font("Century Gothic", 2, 12)); // NOI18N
        txtApellido.setToolTipText("Ingrese Apellido");
        getContentPane().add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 250, -1));

        txtNombre.setFont(new java.awt.Font("Century Gothic", 2, 12)); // NOI18N
        txtNombre.setToolTipText("Ingrese Nombre");
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 250, -1));

        txtCedula.setFont(new java.awt.Font("Century Gothic", 2, 12)); // NOI18N
        txtCedula.setToolTipText("Ingrese Cedula");
        getContentPane().add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 250, -1));

        lblRegresar.setFont(new java.awt.Font("Century Gothic", 2, 12)); // NOI18N
        lblRegresar.setForeground(new java.awt.Color(255, 255, 255));
        lblRegresar.setText("Regresar");
        lblRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegresarMouseClicked(evt);
            }
        });
        getContentPane().add(lblRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, -1, -1));

        lblContraseña.setFont(new java.awt.Font("Century Gothic", 2, 18)); // NOI18N
        lblContraseña.setForeground(new java.awt.Color(255, 255, 255));
        lblContraseña.setText("Contraseña:");
        getContentPane().add(lblContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 120, 30));

        lblPuesto.setFont(new java.awt.Font("Century Gothic", 2, 18)); // NOI18N
        lblPuesto.setForeground(new java.awt.Color(255, 255, 255));
        lblPuesto.setText("Puesto:");
        getContentPane().add(lblPuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 100, 30));

        lblCorreo.setFont(new java.awt.Font("Century Gothic", 2, 18)); // NOI18N
        lblCorreo.setForeground(new java.awt.Color(255, 255, 255));
        lblCorreo.setText("Correo:");
        getContentPane().add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 80, 30));

        lblTelefono.setFont(new java.awt.Font("Century Gothic", 2, 18)); // NOI18N
        lblTelefono.setForeground(new java.awt.Color(255, 255, 255));
        lblTelefono.setText("Telefono:");
        getContentPane().add(lblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 90, 30));

        lblSApellido.setFont(new java.awt.Font("Century Gothic", 2, 18)); // NOI18N
        lblSApellido.setForeground(new java.awt.Color(255, 255, 255));
        lblSApellido.setText("Segundo Apellido:");
        getContentPane().add(lblSApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 180, 30));

        lblApellido.setFont(new java.awt.Font("Century Gothic", 2, 18)); // NOI18N
        lblApellido.setForeground(new java.awt.Color(255, 255, 255));
        lblApellido.setText("Apellido:");
        getContentPane().add(lblApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 80, 30));

        lblNombre.setFont(new java.awt.Font("Century Gothic", 2, 18)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("Nombre:");
        getContentPane().add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 80, 30));

        lblCedula.setFont(new java.awt.Font("Century Gothic", 2, 18)); // NOI18N
        lblCedula.setForeground(new java.awt.Color(255, 255, 255));
        lblCedula.setText("Cedula:");
        getContentPane().add(lblCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 80, 30));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inicioo.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-300, 0, 1110, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void lblRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegresarMouseClicked
        // Regresar al login
        // Ir a la ventana registro
        dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_lblRegresarMouseClicked

    private void btnSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolicitudActionPerformed
        String cedula = txtCedula.getText();
        String nombre = txtNombre.getText();
        String apellido1 = txtApellido.getText();
        String apellido2 = txtSApellido.getText();
        String telefono = txttelefono.getText();
        String correo = txtCorreo.getText();
        String puesto = txtDireccion.getText();
        char[] contrasenaChars = txtContraseña.getPassword();
        String contrasena = new String(contrasenaChars).strip();

        try {
            // Establecer una conexión con el servidor
            Socket socket = new Socket("localhost", 8888);

            // Crear un stream de escritura para enviar la solicitud al servidor
            OutputStream outputStream = socket.getOutputStream();
            PrintWriter writer = new PrintWriter(outputStream, true);

            // Construir la solicitud en el formato adecuado
            String solicitud = "ADMI " + cedula + "&" + nombre + "&" + apellido1 + "&" + apellido2 + "&" + telefono + "&" + correo + "&" + puesto + "&" + contrasena;

            // Enviar la solicitud al servidor
            writer.println(solicitud);

            // Crear un lector de entrada para recibir la respuesta del servidor
            InputStream inputStream = socket.getInputStream();
            BufferedReader reader = new BufferedReader(new InputStreamReader(inputStream));

            // Leer la respuesta del servidor
            String respuesta = reader.readLine();

            // Verificar la respuesta del servidor
            if (respuesta != null && respuesta.trim().toLowerCase().equals("registro administrador")) {
                JOptionPane.showMessageDialog(this, "Registro Administrador.");
            } else {
                JOptionPane.showMessageDialog(this, "Error al registrar los datos.");
            }

            // Cerrar la conexión con el servidor
            socket.close();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error de conexión: " + ex.getMessage());
        }
   
    }//GEN-LAST:event_btnSolicitudActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton btnSolicitud;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPuesto;
    private javax.swing.JLabel lblRegresar;
    private javax.swing.JLabel lblSApellido;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtSApellido;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables
}
